language: node_js
node_js:
  - 7
sudo: required
addons:
  chrome: stable
before_script:
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
        #- which chrome
        #- npm run test:unit
   - npm run test:e2e
  # - npm run bulit
git:
  depth: false
cache:
  directories:
  - node_modules
