language: node_js
node_js:
  - 7
sudo: required
addons:
  chrome: stable
before_script:
        # - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
   - npm run test:unit
git:
  depth: false
cache:
  directories:
  - node_modules
