language: node_js
node_js:
  - 7
before_script:
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - npm run test:unit
  - npm run test:e2e
  - npm run bulit
git:
  depth: false
cache:
  directories:
  - node_modules
